name: build

on:
  push:
    branches:
      - ekfac
  pull_request:
    branches:
      - ekfac
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,faiss]"
      # TODO: Proper test infrastructure for tests/ekfac_tests
      # - name: Run tests
      #   run: pytest
      # TODO: run pyright on whole codebase
      - name: Type Checking bergson/hessians
        uses: jakebailey/pyright-action@v1
        with:
          version: 1.1.406
          working-directory: bergson/hessians
      - name: Type Checking tests/ekfac_tests
        uses: jakebailey/pyright-action@v1
        with:
          version: 1.1.406
          working-directory: tests/ekfac_tests
      - name: build
        run: pip wheel --no-deps -w dist .
env:
  HF_HUB_DOWNLOAD_TIMEOUT: 100
